version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: surveiv2_app_dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    networks:
      - surveiv2_dev_network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=surveiv2_dev
      - DB_USERNAME=surveiv2_user
      - DB_PASSWORD=surveiv2_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

  db:
    image: mysql:8.0
    container_name: surveiv2_db_dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: surveiv2_dev
      MYSQL_USER: surveiv2_user
      MYSQL_PASSWORD: surveiv2_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_dev_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    networks:
      - surveiv2_dev_network

  redis:
    image: redis:7-alpine
    container_name: surveiv2_redis_dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - surveiv2_dev_network

  mailhog:
    image: mailhog/mailhog
    container_name: surveiv2_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - surveiv2_dev_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: surveiv2_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: surveiv2_user
      PMA_PASSWORD: surveiv2_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - surveiv2_dev_network
    depends_on:
      - db

volumes:
  db_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  surveiv2_dev_network:
    driver: bridge
